### ISSUE TITLE
perltidy does not work with -enc=utf8 set

### ISSUE THREAD

**Issue by oschwald** [houseabsolute/perl-code-tidyall#84] opened 2017-09-27 02:10 UTC
When tidying with `-enc=utf8` set, `tidyall` generates warnings:

```
Wide character in print at /home/greg/perl5/perlbrew/perls/perl-5.26.1/lib/site_perl/5.26.1/Path/Tiny.pm line 537.
Wide character in subroutine entry at /home/greg/perl5/perlbrew/perls/perl-5.26.1/lib/site_perl/5.26.1/Code/TidyAll/CacheModel.pm line 125.
```

`perltidy`, by itself, works fine.

Also, the file becomes corrupt in some cases.

@oalders noticed this behavior.

**Comment by autarch** [comment] 2017-10-13 03:08
TidyAll's encoding handling could really use some love. I've wanted to go through and think through it end to end for each plugin. Ideally, TidyAll would know (somehow) exactly what each plugin spits out and whether it's raw bytes or UTF-8 character data. I think in this case what happens is that without that flag, perltidy produces raw bytes and TidyAll just passes them through untouched, leading to the right result in the end (somewhat by accident). With the flag, perltidy returns character data and TidyAll is not prepared to handle it.

**Comment by cxw42** [comment] 2020-04-11 18:10
I have the same issue - MCVE attached as [tidyall-issue84-example.tar.gz](https://github.com/houseabsolute/perl-code-tidyall/files/4465114/tidyall-issue84-example.tar.gz).  To reproduce:

    $ tar xvzf tidyall-issue84-example.tar.gz
    $ cd tidyall-issue84-example
    $ tidyall -a

Thanks!

**Comment by shancock9** [comment] 2022-02-16 23:41
The latest release of Perl::Tidy has a flag to fix this. To set it, update to Perl::Tidy version 20220317 and add the flag `-eos` (`--encode-output-strings`). This flag is needed to resolve an ambiguity in the transfer of string data from Perl::Tidy to Code::Tidyall. If there is a workaround of the form `-enc='none'` it should be removed ( it is not failsafe ). To let perltidy determine the encoding, you can leave `-enc` and `-utf8` undefined.  This should fix the problem.

Here is an explanation. This appears to be the same issue as Perl::Tidy issue git #83 at https://github.com/perltidy/perltidy/issues/83
submitted by Kenneth Ölwing last month, who diagnosed the problem and worked out a solution. The problem is that Perl::Tidy is returning unencoded strings, but TidyAll needs encoded strings.

To fix this, the latest release to CPAN of Perl::Tidy has a new flag, `--encode-output-strings`, or `-eos`, which allows a calling program to request that perltidy encode any strings that it decodes.  (Perl::Tidy always does this when writing files, the issue only arises when passing strings to another perl program).  I intend to make this the default in a future release (see below), but changing the default behavior without warning could break some existing programs because, if they also encrypt the returned string, data will be corrupted.  So, for now, the default behavior is unchanged and the new flag is needed to fix things.

I tested this new flag by adding `-eos` to the perltidyrc file in the above example supplied by `cxw42` and it worked, both with and without the `-utf8` flag (no more 'wide character' messages).

Documentation for using the flag in a program which calls Perl::Tidy is under the heading `destination` at https://metacpan.org/pod/Perl::Tidy.

To illustrate how TidyAll might be modified to supply the flag, so that individual users do not need to, I tested the following code in the Plugin PerlTidy.pm:

```
    # Add --encode-output-strings (-eos) for PT releases in 2022 and later
    # to tell perltidy that we want encoded character strings returned.  See
    # https://github.com/houseabsolute/perl-code-tidyall/issues/84
    # https://github.com/perltidy/perltidy/issues/83
    my $argv = $self->argv;
    $argv .= " -eos" if ( $Perl::Tidy::VERSION > 20220101 );

    $output = capture_merged {
        $error_flag = Perl::Tidy::perltidy(
            argv        => $argv,
            source      => \$source,
            destination => \$destination,
            stderr      => \$stderr,
            errorfile   => \$errorfile
        );
    };
```

I updated my version of tidyall to use this and tested it on the test case mentioned above, using the original `perltidyrc` (without `-eos`), and it worked.  It also worked without the `-utf8` flag.

In the above line of code

```
   $argv .= " -eos" if ( $Perl::Tidy::VERSION > 20220101 );
```

the test on VERSION insures that this will work with older version of Perl::Tidy (releases before year 2022), which would not recognize the `-eos` flag (and would exit with an error). There was no release of Perl::Tidy on 20220101, this is just a convenient number between releases before and after the new flag (v 20211029 and v 20220217).

Also, it is worth noting that in this code the '-eos' flag is added at the end of $argv to insure that it has priority over any user setting.  This will avoid any potential future conflict in case a user might have multiple applications requiring different settings.  I tested this on the above example by supplying an incorrect setting '-neos' in the perltidyrc file.  As expected, the formatting still worked correctly since this incorrect setting got overriden by the value in the Plugin code.

I hope this the final "bump in the road" in getting perltidy working smoothly with utf8 text. As mentioned above, I would like to change the default setting for the new flag in Perl::Tidy to be `-eos` instead of `-neos`, perhaps by the first release in 2023. I will open an issue about this on the github site for Perl::Tidy.  I don't know if there are any existing applications which could have data corrupted by such a change in default, but if there are it is important that they be updated to set `-neos` before the default is changed.  If anyone knows of such an application, please inform the author.  If it isn't clear which setting to use, the easiest thing to do would be to run tests with both possible settings, `-neos` and `-eos`, on utf8 text.

**Comment by autarch** [comment] 2022-02-17 03:24
Thanks, this is fixed in the latest release (with a recent Perl::Tidy, of course).

**Closed** 2022-02-17 03:24 UTC
